version: "3.7"
services:
  roo:
    image: sfproductlabs/roo:latest
    # command: valgrind --tool=memcheck --vgdb=yes --leak-check=yes --track-origins=yes --progress-interval=600 /app/roo/rood /app/roo/roo/config.json
    # command: tail -F test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - forenet
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.load_balancer == true 
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    environment:
      - SWARM_NODE={{.Node.Hostname}}
      - ROO_DNS=tasks.roo_roo.
      - ROO_RESOLVER=127.0.0.11
      - ROO_START_DELAY=10
      - ROO_ACME_STAGING=false
    logging:
      options:
          max-size: "50m"
          
networks:
  forenet:
    driver: overlay
    external: true    
