version: "3.7"
services:
  test:
    image: nginx
    deploy:
      #Set the number of instances of the app you want to run here
      #you can use global to run a single instance on every machine instead
      replicas: 3
    networks:
      - forenet
    labels:
      # curl -X PUT roo_roo:6299/roo/v1/kv/com.roo.host:test.sfpl.io:https -d 'http://test_test:80'
      # - com.roo.host:test.sfpl.io:https=http://test_test:80
      OriginHosts: test.sfpl.io
      OriginScheme: https
      OriginPort: 443
      DestinationHost: test_test
      DestinationScheme: http
      DestinationPort: 80
    
networks:
  forenet:
    external: true          