#ansible-playbook swarm-init.yml -u root
---
    - hosts: workers
      tasks:
        - name: Install docker and join swarm
          shell: |
            apt-get update && \
            apt-get upgrade -y && \
            apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y && \
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - && \
            apt-key fingerprint 0EBFCD88 && \
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
            apt-get update && \
            apt-get install docker-ce docker-ce-cli containerd.io ansible -y && \ 